// Google Gemini AI Assistant & Universal Travel Concierge Service

import { DESTINATIONS } from "../destinations-data.js";

class GeminiService {
  constructor() {
    this.apiKey = localStorage.getItem("voyage_gemini_key") || "";
    this.model = "gemini-2.5-flash";
    this.chatHistory = [];
  }

  setApiKey(key) {
    this.apiKey = (key || "").trim();
    localStorage.setItem("voyage_gemini_key", this.apiKey);
  }

  getApiKey() {
    return this.apiKey;
  }

  hasApiKey() {
    return !!this.apiKey;
  }

  clearChatHistory() {
    this.chatHistory = [];
  }

  /**
   * Conversational Chat with WanderAI: Handles ANY travel question
   */
  async sendMessage(userMessage, destinationContext = null) {
    // 1. Detect if the user's message specifically mentions another destination
    const mentionedDest = this.detectDestinationMention(userMessage);
    const activeDest = mentionedDest || destinationContext || DESTINATIONS[0];

    // 2. If an API key is provided, attempt live Google Gemini API
    if (this.apiKey) {
      try {
        let contextNote = "";
        if (activeDest) {
          contextNote = `[Active Destination: ${activeDest.name}, ${activeDest.country}. Region: ${activeDest.region || activeDest.continent}. Vibes: ${activeDest.vibes?.join(", ")}. Currency: ${activeDest.currency}. Language: ${activeDest.language}. Best season: ${activeDest.bestTimeToVisit}. Daily budget: ~$${activeDest.budgetDailyEstimate} USD.]`;
        }
        const promptText = contextNote ? `${contextNote}\n\nVisitor Question: ${userMessage}` : userMessage;

        const reply = await this.callGeminiApi(promptText);
        this.chatHistory.push({ role: "user", text: userMessage });
        this.chatHistory.push({ role: "model", text: reply });
        return { text: reply, isLive: true };
      } catch (err) {
        console.warn("Gemini API call error (falling back to Universal Travel Engine):", err);
      }
    }

    // 3. Fallback: Universal Travel Knowledge Engine (Answers ANY question)
    const reply = this.generateUniversalTravelAnswer(userMessage, activeDest);
    this.chatHistory.push({ role: "user", text: userMessage });
    this.chatHistory.push({ role: "model", text: reply });
    return { text: reply, isLive: false };
  }

  detectDestinationMention(msg) {
    const q = (msg || "").toLowerCase();
    for (const d of DESTINATIONS) {
      if (q.includes(d.name.toLowerCase()) || q.includes(d.id.toLowerCase())) {
        return d;
      }
    }
    return null;
  }

  async callGeminiApi(promptText) {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${this.model}:generateContent?key=${this.apiKey}`;

    const systemPrompt = "You are WanderAI, an elite, worldly travel concierge and guide. You answer ANY question asked about travel, history, destinations, landmarks, culture, food, safety, transit, budgeting, etiquette, weather, and packing. Format responses cleanly with bold titles and bullet points for readability. Be engaging, practical, accurate, and deeply knowledgeable.";

    const contents = [
      ...this.chatHistory.slice(-6).map((msg) => ({
        role: msg.role,
        parts: [{ text: msg.text }]
      })),
      {
        role: "user",
        parts: [{ text: promptText }]
      }
    ];

    const response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        systemInstruction: {
          parts: [{ text: systemPrompt }]
        },
        contents,
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 1200
        }
      })
    });

    if (!response.ok) {
      const errBody = await response.text();
      throw new Error(`Gemini API error (${response.status}): ${errBody}`);
    }

    const data = await response.json();
    const candidate = data.candidates?.[0];
    if (!candidate || !candidate.content?.parts?.[0]?.text) {
      throw new Error("No response generated by Gemini model");
    }

    return candidate.content.parts[0].text;
  }

  /**
   * Universal Travel Knowledge Engine: Answers ANY question across destinations, topics, and landmarks
   */
  generateUniversalTravelAnswer(query, dest) {
    const q = (query || "").toLowerCase().trim();
    const destName = dest ? dest.name : "your destination";
    const country = dest ? dest.country : "";

    // 1. GREETINGS & CASUAL
    if (/^(hi|hello|hey|greetings|hola|namaste|bonjour|good (morning|afternoon|evening))/i.test(q)) {
      return `Hello! I'm **WanderAI**, your personal global travel concierge. I'm ready to answer any questions about **${destName}** (${country}) or any other worldwide destination.\n\nYou can ask me about:\n• Iconic landmarks and hidden gems\n• Local dining, street food & signature dishes\n• Safety, solo travel, and local transit\n• Currency, budgeting, and tipping etiquette\n• Packing tips and optimal times to visit\n\nWhat would you like to explore?`;
    }

    if (q.includes("who are you") || q.includes("what can you do")) {
      return `I am **WanderAI**, an AI travel specialist designed to help you explore destinations around the world. I can answer questions about any destination or landmark, recommend local cuisines, provide safety and transit advice, estimate budgets, and generate custom day-by-day itineraries!`;
    }

    if (q.includes("joke") || q.includes("funny")) {
      const jokes = [
        "Why do travelers love exploring ancient ruins? Because they really appreciate a place with *good foundations*!",
        "Why did the airplane get sent to its room? Because it had a bad *altitude*!",
        "What is an astronaut's favorite part of a computer? The *Space* bar!"
      ];
      return jokes[Math.floor(Math.random() * jokes.length)];
    }

    // 2. SPECIFIC FAMOUS LANDMARK QUESTIONS
    if (dest?.famousPlaces) {
      for (const place of dest.famousPlaces) {
        if (q.includes(place.name.toLowerCase()) || q.includes(place.id.toLowerCase()) || (place.wikiTitle && q.includes(place.wikiTitle.toLowerCase()))) {
          return `### 🏛️ **${place.name}** (${place.category})
**Location:** ${dest.name}, ${dest.country} · **Rating:** ★ ${place.rating} (${place.reviewsCount?.toLocaleString()} reviews)

**Overview:**
${place.description}

**Why You Must Experience It:**
> "${place.whyVisit}"

**Visitor Guidelines & Pro-Tips:**
• **Estimated Duration:** ${place.estimatedTime}
• **Admission Cost:** ${place.entryCost}
• **Insider Pro-Tip:** ${place.insiderTip}

*Would you like me to incorporate ${place.name} into a custom day-by-day itinerary for ${dest.name}?*`;
        }
      }
    }

    // Also check other landmarks across ALL destinations if mentioned by name
    for (const otherDest of DESTINATIONS) {
      for (const place of otherDest.famousPlaces) {
        if (q.includes(place.name.toLowerCase())) {
          return `### 🏛️ **${place.name}** (${place.category})
**Location:** ${otherDest.name}, ${otherDest.country} · **Rating:** ★ ${place.rating}

**Overview:**
${place.description}

**Why You Must Experience It:**
> "${place.whyVisit}"

**Visitor Tips:**
• **Estimated Time:** ${place.estimatedTime}
• **Admission:** ${place.entryCost}
• **Pro-Tip:** ${place.insiderTip}`;
        }
      }
    }

    // 3. SAFETY, SOLO TRAVEL, CRIME & HEALTH
    if (q.includes("safe") || q.includes("crime") || q.includes("danger") || q.includes("scam") || q.includes("emergency") || q.includes("solo female")) {
      return `### 🛡️ Safety & Travel Awareness in **${destName}**
**Safety Rating:** ${dest.safetyRating || "High"}

**Key Guidelines:**
• **General Security:** ${destName} is generally very welcoming to global travelers. Maintain standard urban alertness in crowded tourist centers.
• **Common Scams to Avoid:** Beware of unofficial ticket scalpers near major monuments, overpriced unmarked taxis, and distracting street petitions.
• **Solo & Evening Travel:** Stroll along well-lit main boulevards and waterfront promenades. Use licensed ride-hailing apps (Uber, local metered taxis) after midnight.
• **Emergency Assistance:** Keep your embassy/consulate phone number and hotel address card in the local language saved on your phone.`;
    }

    // 4. TRANSPORTATION, GETTING AROUND & AIRPORT
    if (q.includes("transport") || q.includes("metro") || q.includes("bus") || q.includes("subway") || q.includes("train") || q.includes("uber") || q.includes("taxi") || q.includes("airport") || q.includes("get around")) {
      return `### 🚇 Getting Around **${destName}**

**Public Transit & Rail:**
• Use the city's contactless payment or official transit IC/smart card for seamless rides across buses, metros, and urban commuter trains.
• High-speed rail and regional trains connect ${destName} efficiently to surrounding provinces and scenic day trips.

**Ride-Hailing & Taxis:**
• Licensed taxis and apps (like Uber or official airport transit counters) are reliable. Always ensure the meter is running or pre-book via app to avoid inflated fares.

**Airport Transfer:**
• Dedicated express trains and official airport shuttle buses offer the fastest, most economical route directly into the central station and hotel districts.`;
    }

    // 5. CURRENCY, MONEY, CARDS, ATMS & TIPPING
    if (q.includes("currency") || q.includes("money") || q.includes("card") || q.includes("cash") || q.includes("atm") || q.includes("tipping") || q.includes("tip")) {
      return `### 💳 Currency & Payments in **${destName}**
**Official Currency:** ${dest.currency || "Local Currency"}

**Payment Recommendations:**
• **Cards vs. Cash:** Major credit cards (Visa, Mastercard) and mobile tap-to-pay are widely accepted at hotels, restaurants, and department stores. However, carry a moderate amount of cash for traditional street vendors, local transit, and flea markets.
• **ATMs:** Always use ATMs physically located inside recognized bank branches rather than standalone machines to avoid skimming fees.
• **Tipping Customs:** 
  - In ${dest.country}: Tipping customs vary by culture. In places like Japan, tipping is not practiced; in Europe, rounding up 5–10% is polite for great service; in North America, 18–20% is standard. Check your bill for included service charges (*service compris*).`;
    }

    // 6. FOOD, DINING, RESTAURANTS & SPECIALTIES
    if (q.includes("eat") || q.includes("food") || q.includes("dish") || q.includes("restaurant") || q.includes("cuisine") || q.includes("dinner") || q.includes("breakfast") || q.includes("street food")) {
      const foodList = dest?.localCuisine ? dest.localCuisine.map(f => `• **${f}**`).join("\n") : "• Regional artisan specialties\n• Authentic street food delicacies";
      return `### 🍽️ Culinary Highlights in **${destName}**

Here are the signature culinary must-haves you shouldn't leave without tasting:

${foodList}

**Dining Etiquette & Pro-Tips:**
• Step 1 to 2 streets away from major monument squares to discover beloved family-run trattorias, izakayas, and local bistros with authentic flavors and honest prices.
• Peak dinner hours usually begin around 7:30 PM–8:30 PM. For Michelin-recommended or viral spots, reservations are highly recommended 2–3 weeks in advance.`;
    }

    // 7. SIGHTSEEING, WHAT TO SEE & ATTRACTIONS
    if (q.includes("what to see") || q.includes("attraction") || q.includes("places to visit") || q.includes("landmark") || q.includes("sightseeing") || q.includes("must see")) {
      const placesList = dest?.famousPlaces ? dest.famousPlaces.map(p => `• **${p.name}** (${p.category}) — *${p.whyVisit}*`).join("\n") : "• Historic City Center and Royal Palaces\n• Scenic Waterfronts and Lookout Points";
      return `### 🌟 Notable Places to Visit in **${destName}**

Here are the iconic, handpicked landmarks:

${placesList}

**Pro-Tip:** Book advance morning time slots for the top attractions to bypass ticket lines and enjoy peaceful photography!`;
    }

    // 8. DURATION & HOW LONG TO STAY
    if (q.includes("how long") || q.includes("how many days") || q.includes("duration") || q.includes("spend")) {
      return `### ⏱️ Recommended Stay for **${destName}**
**Optimal Duration:** **${dest.idealDuration || "4 to 6 days"}**

**Suggested Pace:**
• **Days 1–2:** Orientation, historic quarter, and signature landmark visits.
• **Days 3–4:** Cultural museums, neighborhood strolls, culinary immersion, and sunset overlooks.
• **Days 5+:** Scenic day trips to surrounding valleys, beaches, or historic castles.

*Tip: You can use the AI Itinerary Planner tab above to generate a custom day-by-day plan tailored to your duration!*`;
    }

    // 9. WHEN TO VISIT, SEASONS & WEATHER
    if (q.includes("when to go") || q.includes("best time") || q.includes("season") || q.includes("weather") || q.includes("month") || q.includes("rain") || q.includes("winter") || q.includes("summer")) {
      return `### 🌤️ Best Time to Visit **${destName}**
**Prime Season:** **${dest.bestTimeToVisit || "Spring & Autumn"}**

**Seasonal Overview:**
• **Peak Months:** Offer mild, comfortable temperatures and clear skies ideal for outdoor exploration.
• **Off-Peak / Shoulder Seasons:** Yield fewer tourist crowds and significantly more affordable flight and hotel rates.
• Check the **Real-Time Weather** tab on this page to see live temperatures and our 5-day meteorological forecast!`;
    }

    // 10. PACKING & WHAT TO WEAR
    if (q.includes("pack") || q.includes("wear") || q.includes("dress") || q.includes("shoes") || q.includes("clothes")) {
      return `### 🎒 Packing Essentials for **${destName}**

1. **Footwear:** Broken-in walking shoes or cushioned sneakers (you will easily log 10,000–18,000 steps daily on cobblestone or pavement).
2. **Layering:** Breathable lightweight clothing with a compact waterproof shell jacket for unexpected showers.
3. **Modesty Attire:** If visiting sacred shrines, churches, or temples, bring a lightweight scarf or clothing that covers shoulders and knees.
4. **Tech & Power:** Universal travel power adapter, high-capacity power bank, and a digital e-SIM.
5. **Sun & Hydration:** UV-blocking sunglasses, high SPF sunscreen, and a reusable insulated water bottle.`;
    }

    // 11. BUDGET & EXPENSES
    if (q.includes("budget") || q.includes("cost") || q.includes("how much") || q.includes("price") || q.includes("expensive") || q.includes("cheap")) {
      const daily = dest.budgetDailyEstimate || 100;
      return `### 💰 Budget & Cost Guide for **${destName}**
**Budget Tier:** ${dest.budget || "$$"} · **Daily Estimate:** ~**$${daily} USD** per person

**Estimated Breakdown:**
• **Accommodations:** $40–$80 (budget/hostel) | $120–$250 (boutique/comfort)
• **Meals & Dining:** $20–$50/day (delicious street food & local trattorias)
• **Transit & Sightseeing:** $15–$30/day (passes and monument entries)
• **Money-Saving Tip:** Pick up public transit day-passes and look out for free entry days at major national museums.`;
    }

    // 12. SHOPPING, SOUVENIRS & MARKETS
    if (q.includes("shop") || q.includes("souvenir") || q.includes("market") || q.includes("bazaar") || q.includes("buy")) {
      return `### 🛍️ Shopping & Souvenirs in **${destName}**

**What to Look For:**
• Authentic handmade artisanal crafts, local ceramics, textiles, and regional teas or spices.
• Avoid mass-produced plastic trinkets; seek out certified local artisan cooperatives or historic market stalls.
• Remember to ask for VAT / Tax-Free shopping forms at major stores if you are an international traveler.`;
    }

    // 13. NIGHTLIFE, EVENING & SUNSET
    if (q.includes("night") || q.includes("evening") || q.includes("sunset") || q.includes("bar") || q.includes("club") || q.includes("party")) {
      return `### 🌆 Twilight & Nightlife in **${destName}**

**Evening Recommendations:**
• **Sunset Vantage Points:** Watch the golden hour light up the city skyline or coastline from scenic rooftop lounges and elevated bridges.
• **Night Markets & Walking Streets:** Wander illuminated historic quarters where street food stalls and lively artisan shops stay buzzing after dark.
• **Cocktails & Music:** Sample craft local brews, signature cocktails, and live traditional or acoustic jazz performances in cozy local alleys.`;
    }

    // 14. CULTURE, ETIQUETTE & CUSTOMS
    if (q.includes("culture") || q.includes("etiquette") || q.includes("custom") || q.includes("polite") || q.includes("rule") || q.includes("respect")) {
      const tips = dest.travelTips ? dest.travelTips.map(t => `• ${t}`).join("\n") : "• Respect sacred religious sanctuaries\n• Greet shopkeepers respectfully upon entering";
      return `### 🎎 Local Etiquette & Customs in **${destName}**

${tips}

**Key Cultural Advice:**
• A few words in the local language (*"Thank you"*, *"Hello"*, *"Please"*) go an extraordinarily long way in winning warm local smiles.
• Always ask permission before photographing local artisans, monks, or performing street artists.`;
    }

    // 15. DESTINATION COMPARISON
    if (q.includes("compare") || q.includes("vs") || q.includes("versus") || q.includes("or")) {
      return `### ⚖️ Travel Comparison & Insights
Both destinations offer distinct, world-class magic:
• **${destName}** excels in ${dest.vibes?.join(", ") || "culture and iconic scenery"}, making it exceptional for ${dest.tagline || "unforgettable journeys"}.
• Depending on whether your priority is relaxation, adventurous exploration, or deep historic immersion, I can tailor your schedule to either one! Which vibe are you leaning toward?`;
    }

    // 16. GENERAL / SEMANTIC FALLBACK
    return `### 🌍 WanderAI Concierge: **${destName}** (${dest.country})

Regarding your inquiry about **"${query}"**:

**Key Insights for ${destName}:**
• **Character & Vibe:** ${dest.tagline || dest.summary}
• **Region & Culture:** ${dest.region || dest.continent} (${dest.language} speaking).
• **Practical Advice:** ${dest.travelTips?.[0] || "Plan visits to popular monuments early in the morning to beat the peak crowds."}
• **Culinary Note:** Be sure to sample ${dest.localCuisine?.[0] || "authentic local cuisine"} during your stay.

*Feel free to ask me anything else — whether about safety, hidden gems, budget breakdowns, or click **"AI Itinerary Planner"** in the top navigation to build a complete day-by-day expedition!*`;
  }

  /**
   * Generate Structured Day-by-Day Itinerary with Authentic Landmark Photography
   */
  async generateItinerary({ destination, days = 3, travelStyle = "Balanced", interests = [], originCity = "" }) {
    if (this.apiKey) {
      try {
        const structuredData = await this.callGeminiForItinerary({ destination, days, travelStyle, interests, originCity });
        if (structuredData && structuredData.days) {
          this.enrichItineraryWithRealImages(structuredData, destination);
          return { itinerary: structuredData, isLive: true };
        }
      } catch (err) {
        console.warn("Live Gemini Itinerary failed, using curated itinerary engine:", err);
      }
    }

    const fallbackItinerary = this.generateCuratedItinerary({ destination, days, travelStyle, interests, originCity });
    return { itinerary: fallbackItinerary, isLive: false };
  }

  enrichItineraryWithRealImages(itinerary, destination) {
    if (!itinerary || !itinerary.days || !destination) return itinerary;
    const places = destination.famousPlaces || [];
    const nearby = destination.nearbyPlaces || [];
    const allPlaces = [...places, ...nearby];

    itinerary.heroImage = destination.heroImage;

    itinerary.days.forEach((day, dIdx) => {
      const slots = ["morning", "afternoon", "evening"];
      slots.forEach((slotKey, sIdx) => {
        const slot = day[slotKey];
        if (slot) {
          const sTitle = (slot.title || "").toLowerCase();
          const matched = allPlaces.find(p => 
            sTitle.includes(p.name.toLowerCase()) || p.name.toLowerCase().includes(sTitle)
          );
          if (matched && matched.image) {
            slot.image = matched.image;
          } else if (places.length > 0) {
            const fallbackIdx = (dIdx * 2 + sIdx) % places.length;
            slot.image = places[fallbackIdx].image;
          } else {
            slot.image = destination.heroImage;
          }
        }
      });
      day.heroImage = day.morning?.image || destination.heroImage;
    });

    return itinerary;
  }

  async callGeminiForItinerary({ destination, days, travelStyle, interests, originCity }) {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${this.model}:generateContent?key=${this.apiKey}`;

    const prompt = `Generate a realistic, detailed day-by-day travel itinerary for a ${days}-day trip to ${destination.name}, ${destination.country}.
Travel Style: ${travelStyle}
Traveler Interests: ${interests.join(", ") || "Culture, Food, Sightseeing, Photography"}
${originCity ? `Departing from: ${originCity}` : ""}

Return ONLY valid JSON with no markdown backticks, matching this exact structure:
{
  "tripTitle": "string",
  "destination": "${destination.name}, ${destination.country}",
  "totalDays": ${days},
  "travelStyle": "${travelStyle}",
  "estimatedBudgetUSD": "string (e.g. $600 - $800)",
  "overview": "string (2 sentences summarizing the trip narrative)",
  "packingEssentials": ["string", "string", "string", "string"],
  "days": [
    {
      "dayNumber": 1,
      "title": "string (catchy theme for the day)",
      "morning": {
        "time": "09:00 AM",
        "title": "string",
        "description": "string (concise practical guide)",
        "tag": "Culture | Nature | Dining | Adventure | Relaxation",
        "cost": "Free | $ | $$ | $$$"
      },
      "afternoon": {
        "time": "01:30 PM",
        "title": "string",
        "description": "string",
        "tag": "Culture | Nature | Dining | Adventure | Relaxation",
        "cost": "Free | $ | $$ | $$$"
      },
      "evening": {
        "time": "06:30 PM",
        "title": "string",
        "description": "string",
        "tag": "Culture | Nature | Dining | Adventure | Relaxation",
        "cost": "Free | $ | $$ | $$$"
      },
      "foodHighlight": "string (specific dish and spot to try)",
      "insiderTip": "string (pro advice to save time or avoid hassle)"
    }
  ]
}`;

    const response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.4,
          responseMimeType: "application/json"
        }
      })
    });

    if (!response.ok) {
      throw new Error(`Gemini Itinerary HTTP ${response.status}`);
    }

    const data = await response.json();
    const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!rawText) throw new Error("Empty response from Gemini");

    const cleaned = rawText.replace(/```json/g, "").replace(/```/g, "").trim();
    return JSON.parse(cleaned);
  }

  generateCuratedItinerary({ destination, days = 3, travelStyle = "Balanced", interests = [], originCity = "" }) {
    const dailyBudget = destination.budgetDailyEstimate || 100;
    const totalEstimate = `$${dailyBudget * days} – $${Math.round(dailyBudget * days * 1.3)} USD`;

    const places = destination.famousPlaces || [];
    const nearby = destination.nearbyPlaces || [];
    const itineraryDays = [];

    for (let d = 1; d <= days; d++) {
      const primaryPlace = places[(d - 1) % places.length] || { name: "Historic City Center", category: "Sightseeing", image: destination.heroImage };
      const secondaryPlace = places[d % places.length] || { name: "Cultural Quarter & Scenic Overlook", category: "Culture", image: destination.heroImage };
      const nearbyOrPlace = nearby.length > 0 ? nearby[(d - 1) % nearby.length] : places[(d + 1) % places.length] || primaryPlace;

      let theme = `Day ${d}: Iconic Landmarks & Immersion`;
      if (d === 1) theme = `Arrival, Orientation & ${primaryPlace.name}`;
      else if (d === 2) theme = `Deep Heritage & Hidden Neighborhoods`;
      else if (d === 3) theme = `Panoramic Vistas & Artisan Dining`;
      else if (d === 4) theme = nearbyOrPlace ? `Scenic Excursion: ${nearbyOrPlace.name}` : `Scenic Day Trip & Local Markets`;
      else theme = `Leisure, Shopping & Twilight Farewell`;

      itineraryDays.push({
        dayNumber: d,
        title: theme,
        heroImage: primaryPlace.image || destination.heroImage,
        morning: {
          time: "09:00 AM",
          title: `Discover ${primaryPlace.name}`,
          description: `Early morning exploration of ${primaryPlace.name}. Take in the quiet morning atmosphere and snap postcard photos before peak tour arrivals.`,
          tag: primaryPlace.category || "Culture",
          cost: primaryPlace.entryCost || "$$",
          image: primaryPlace.image || destination.heroImage
        },
        afternoon: {
          time: "01:30 PM",
          title: `Stroll through ${secondaryPlace.name}`,
          description: `Enjoy lunch nearby, then proceed to ${secondaryPlace.name}. Immerse yourself in the surrounding artisan streets and architectural details.`,
          tag: secondaryPlace.category || "Sightseeing",
          cost: "$$",
          image: secondaryPlace.image || destination.heroImage
        },
        evening: {
          time: "06:30 PM",
          title: "Golden Hour Stroll & Authentic Dinner",
          description: `Watch the sunset over the city skyline. Unwind at a cozy traditional eatery recommended by locals.`,
          tag: "Dining & Relaxation",
          cost: "$$$",
          image: destination.heroImage || primaryPlace.image
        },
        foodHighlight: destination.localCuisine ? destination.localCuisine[(d - 1) % destination.localCuisine.length] : "Local culinary specialty",
        insiderTip: primaryPlace.insiderTip || "Wear comfortable footwear and carry local currency for market purchases."
      });
    }

    return {
      tripTitle: `${days} Days in ${destination.name}: The ${travelStyle} Journey`,
      destination: `${destination.name}, ${destination.country}`,
      totalDays: days,
      travelStyle,
      estimatedBudgetUSD: totalEstimate,
      overview: `A carefully curated ${days}-day adventure across ${destination.name}, balancing iconic architectural wonders with authentic neighborhood discoveries and world-class regional gastronomy.`,
      packingEssentials: [
        "Comfortable walking shoes with good support",
        "Universal power adapter and portable charging bank",
        "Weather-appropriate layering shell jacket",
        "Daypack with RFID-blocking compartments"
      ],
      heroImage: destination.heroImage,
      days: itineraryDays
    };
  }
}

export const geminiService = new GeminiService();
